id: P006987
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG17449
  title: གསུང་འབུམ། རྒྱལ་མཚན་དཔལ།
  author: ''
  volumes:
    5c8635dd69464b18a97505f136b80efe:
      image_group_id: I1KG18247
      title: ''
      volume_number: 1
      total_pages: 586
    07439e720ebe41489efb2df5e75f31ff:
      image_group_id: I1KG18248
      title: ''
      volume_number: 2
      total_pages: 654
    d338a88df8cd4320a22d9388ad563185:
      image_group_id: I1KG18249
      title: ''
      volume_number: 3
      total_pages: 562
ebook_metadata:
  title: གསུང་འབུམ། རྒྱལ་མཚན་དཔལ།
  author: ''
  sku: P006987
  cover: cover.jpg
  layers:
  - pagination
