id: I662E33D8
legacy_id: P006987
ocr_import_info:
  bdrc_scan_id: W1KG17449
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T12:50:04'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T09:37:09.404923+00:00'
last_modified: 2022-08-31 17:38:09.679081
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17449
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17449
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། རྒྱལ་མཚན་དཔལ།
  author: ཡང་དགོན་པ་རྒྱལ་མཚན་དཔལ།
statistics:
  ocr_word_mean_confidence_index: 0.777276685408163
  ocr_word_median_confidence_index: 0.8500000238418579
quality: null
bases:
  I1KG18247:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18247
      total_pages: 586
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG18247.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7832490842428375
    legacy_id: v001
  I1KG18249:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18249
      total_pages: 562
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG18249.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7756754146571672
    legacy_id: v003
  I1KG18248:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG18248
      total_pages: 654
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG18248.txt
    statistics:
      ocr_word_median_confidence_index: 0.8500000238418579
      ocr_word_mean_confidence_index: 0.7738556823578691
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
