id: I662E33D8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T12:53:49+00:00'
last_modified: '2022-06-08T09:51:27.110258+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17449
  title: གསུང་འབུམ། རྒྱལ་མཚན་དཔལ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    4D8D:
      image_group_id: I1KG18247
      title: Volume 1 of
      total_pages: 586
      order: 1
      base_file: 4D8D.txt
    63E5:
      image_group_id: I1KG18248
      title: Volume 2 of
      total_pages: 654
      order: 2
      base_file: 63E5.txt
    39D2:
      image_group_id: I1KG18249
      title: Volume 3 of
      total_pages: 562
      order: 3
      base_file: 39D2.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
